---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin/"
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: content/posts
  label: Blog Posts
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post
- type: document
  path: content/data/authors.yaml
  label: Author List
- type: document
  path: content/pages/about.md
  label: About Page
- type: heading
  label: General Config
- type: document
  path: config.json
  label: Site Info
- type: document
  path: content/data/strings.yaml
  label: UI Strings
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":year:/:filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: node:14
  mount_path: "/srv"
  working_dir: "/srv/public"
  instant_preview_command: yarn forestry-preview
